# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Cafés del mes',  url: 'cafes-del-mes'}
- {name: 'Tutoriales', url: 'tutoriales'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
- {name: 'Sobre nosotros',       url: 'sobre-nosotros'}
- {name: 'Contacto',            url: 'contacto'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/'}
#- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://instagram.com/cafelitorico'}
- {icon: 'envelope', link:   'mailto:quiero@cafelitorico.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Recientes'
  previous_page: 'Antiguas'

sharing_button_prompt: 'Puedes compartir este contenido'

related_posts: 'También te puede interesar'

post_date_prefix: 'Publicado el'
